- name: install latest qemu-guest-agent
  hosts: "linux"
  tasks:
    - name: isntall qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true